### ISSUE TITLE
/bin/sh: /Users/vagrant/src/opt/local/bin/mtoc.NEW: No such file or directory

### ISSUE THREAD

**Issue by Dids** [Micky1979/Build_Clover#14]
The non-interactive builds are broken again, thanks to mtoc changes (Clover removed mtoc?).

Any chance for a quick fix?

Note that this is similar to the mtoc issue in #9.

**Comment by Dids** [comment]
Just for reference, this commit removed `mtoc.NEW` checking/handling in `ebuild.sh`: https://sourceforge.net/p/cloverefiboot/code/4542/tree//ebuild.sh?diff=504c3833fd48f873331ebd05:4541

I don't know where `mtoc.NEW.zip` is coming from, but that doesn't seem to exist anymore, which is what actually breaks it, at least in non-interactive mode.

**Comment by Dids** [comment]
I don't know what the idea is here. Does Clover not use mtoc anymore, or does it expect it to be installed by default from now on?

**Comment by Dids** [comment]
Extra logs:

```
Building ... /Users/vagrant/src/edk2/AptioFixPkg/Application/CleanNvram/CleanNvram.inf [X64]
Building ... /Users/vagrant/src/edk2/AptioFixPkg/Application/VerifyMsrE2/VerifyMsrE2.inf [X64]
Building ... /Users/vagrant/src/edk2/AptioFixPkg/Platform/AptioMemoryFix/AptioMemoryFix.inf [X64]
[CC] CleanNvram
[CC] VerifyMsrE2
[CC] AutoGen
[CC] AptioMemoryFix
[CC] AutoGen
[SLINK] CleanNvram
[SLINK] VerifyMsrE2
[CC] BootArgs
[CC] BootFixes
[CC] CustomSlide
[DLINK1] VerifyMsrE2
/bin/sh: /Users/vagrant/src/opt/local/bin/mtoc.NEW: No such file or directory
make: *** [/Users/vagrant/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Application/VerifyMsrE2/VerifyMsrE2/DEBUG/VerifyMsrE2.efi] Error 127

build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Application/VerifyMsrE2/VerifyMsrE2]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Application/CleanNvram/CleanNvram]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Platform/AptioInputFix/AptioInputFix]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Platform/AptioMemoryFix/AptioMemoryFix]

build.py...
 : error F002: Failed to build module
	/Users/vagrant/src/edk2/AptioFixPkg/Application/VerifyMsrE2/VerifyMsrE2.inf [X64, XCODE8, RELEASE]
```

**Comment by Dids** [comment]
Both [AptioFixPkg](https://github.com/acidanthera/AptioFixPkg) and the new [ApfsSupportPkg](https://github.com/acidanthera/ApfsSupportPkg) seem to have binary releases now, so maybe Build_Clover could drop building AptioFixPkg altogether, and simply opt to download the drivers instead?

**Comment by Dids** [comment]
I figured out a temporary workaround. If I run the following on a fresh run (no `src` folder), _before_ running `Build_Clover.command`, everything builds fine with a non-interactive configuration:

```bash
MTOC_URL=https://github.com/acidanthera/ApfsSupportPkg/raw/master/External/mtoc-mac64.zip
MTOC_PATH="${HOME}/src/opt/local/bin"
mkdir -p "${MTOC_PATH}"
curl -sSLk $MTOC_URL > "/tmp/mtoc.NEW.zip"
unzip -qo "/tmp/mtoc.NEW.zip" -d "${MTOC_PATH}/"
chmod +x "${MTOC_PATH}/mtoc.NEW"
```

**Comment by philippetev** [comment]
Just added the support for all the above. Thanks anyway!
