### ISSUE TITLE
EDK2 revision doesnt Update

### ISSUE THREAD

**Issue by Gamedev1909** [Micky1979/Build_Clover#3]
So i had to edit the script to update to newest revision of EDK2 could you add a option to choose to use suggested local or the remote please thanks

**Comment by Micky1979** [comment]
Sorry for the late. Lately this repo was not monitored by me so often.
By design this is not possible for the simple fact that edk2 revision in use must be compatible with patches for edk2 made by Clover team. 
Thanks anyway for your suggestion

**Comment by Micky1979** [comment]
Now you can give a command line argument with the desired revision of edk2:

Build_Clover.command --edk2rev <revision>
