### ISSUE TITLE
TODO List and roadmap

### ISSUE THREAD

**Issue by fabiomartino** [Micky1979/Build_Clover#4]
Hi Micky and all other collaborators
---
_This is more a way where we can share and propose changes for this new features_

The idea (basic concept) is to add a cfg file for store the main script value like SVN url repo and user preferences, in this way the final user can "personalize" his preferences
[http://wiki.bash-hackers.org/howto/conffile](url)

**Comment by fabiomartino** [comment]
### Feature concept:

-  Option for handle the buildClover.cfg file within the main script (inside the developer submenu)
-- Remove Create Edit... add "custom repositories"
- Ability to check and load variables from buildClover.cfg, if the buildClover.cfg not exist then create it with stock values
- The pref.cfg file will must place in the same path of the main script (can be deleted if messed up)
- Store stock and custom URLs also from git repositories for both Clover and EDK2
- ...

**Comment by Micky1979** [comment]
Hi all,

I made a concept with a new untested branch named "preferences", please do yours and discuss about what could be the best way.

The target is to have a preferences file + the use of git like Rehabman doing.
This can be callable (imo) as argument for the script or automatically found in the same path where the script reside (to be implemented). As option a variable in your bash profile can be used (if set) as the path to your config file. An idea.

Good night.

**Comment by Micky1979** [comment]
Guys, my prototype is in a working state, see [this commit](https://github.com/Micky1979/Build_Clover/commit/5b3450dd3cec0a7982d657352d5a8a349083aa5d)

USAGE:
Build_Clover.command --cfg=/path/to/a/file.cfg
or
place a Build_Clover.cfg near Build_Clover.command
or set 
export BUILD_CLOVER_CFG_PATH="/path/to/a/file.cfg"
to your bash profile

NOTE:
Build_Clover.command --default 
use default values

...here appear to works well

**Comment by Micky1979** [comment]
Hi guys, I invete you to create your branches with your solutions. Later we can merge all the best from all of us.
