### ISSUE TITLE
Error addTemplateScripts: template 'VBoxHfs' doesn't exists

### ISSUE THREAD

**Issue by hereisderek** [Micky1979/Build_Clover#6]
I'm not very familiar with the structure of this project or clover, so this may be just very stupid, but I encountered with this error:
`Error addTemplateScripts: template 'VBoxHfs' doesn't exists`
when doing a release build. 
so is there a fix or even a way to exclude/skip VBoxHfs (which seems to be causing the issue) from the package at all?

```=============== drivers64 UEFI mandatory ===============
	[BUILD] AppleImageCodec-64.UEFI
	[BUILD] AppleKeyAggregator-64.UEFI
	[BUILD] AppleUITheme-64.UEFI
	[BUILD] DataHubDxe-64.UEFI
	[BUILD] FSInject-64.UEFI
	[BUILD] FirmwareVolume-64.UEFI
	[BUILD] OsxFatBinaryDrv-64.UEFI
	[BUILD] SMCHelper-64.UEFI
Error addTemplateScripts: template 'VBoxHfs' doesn't exists
make: *** [pkg] Error 1
================================================================================
build started at:
Sat Oct 14 18:23:08 NZDT 2017
finished at
Sat Oct 14 18:25:26 NZDT 2017

Done!

                             <--------------------------------------------------
Clover was built successfully!
Press any key to continue...```

**Comment by hereisderek** [comment]
I forgot to mention, my fs is case-sensitive hfs+

**Comment by Micky1979** [comment]
Please attach an entire log. "addTemplateScripts" comes from buildpkg.sh, but it clearly say you that VBoxHfs does not exist.. why?
I'm closing this issue since to skip a driver you have to make a pull request to Clover team at https://sourceforge.net/p/cloverefiboot/code/HEAD/tree/

**Comment by hereisderek** [comment]
[clover.log](https://github.com/Micky1979/Build_Clover/files/1442883/clover.log)
this is the full log from a clean slate (no src folder to start with)

I understand this may be beyond the scope of this script, but just to put it here for anyone encounters the same issue in the future

**Comment by hereisderek** [comment]
i see, so it is actually a bug caused by the case-sensitive file system. the folder is VboxHfs whereas the path it looks for is "package/Scripts.templates/VBoxHfs"

**Comment by Micky1979** [comment]
cannot test this condition, but as I said We cannot do anything for you. Looking at the buildpkg.sh, anyway, there's no one line that says choiceId="VBoxHfs", so I really don't understand why this happened to you. My advice is to delete ~/src/edk2/Clover/CloverPackage/package/buildpkg.sh and call svn up before building again.
